services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: subs
      POSTGRES_PASSWORD: subs
      POSTGRES_DB: subs
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
